finaldata$Sub_metering_1<-as.numeric(finaldata$Sub_metering_1)
finaldata$Sub_metering_2<-as.numeric(finaldata$Sub_metering_2)
finaldata$Sub_metering_3<-as.numeric(finaldata$Sub_metering_3)
plot(finaldata$contime,finaldata$Sub_metering_1,col = "black",ylab = "Global Active Power (kilowatts)", xlab ="" ,type = "l",xaxt="n")
lines(finaldata$contime,finaldata$Sub_metering_2,col = "red",ylab = "Global Active Power (kilowatts)", xlab ="" ,type = "l",xaxt="n")
lines(finaldata$contime,finaldata$Sub_metering_3,col = "blue",ylab = "Global Active Power (kilowatts)", xlab ="" ,type = "l",xaxt="n")
axis(side = 1,at = c(finaldata$contime[1],finaldata$contime[0.5*length(finaldata$contime)],finaldata$contime[length(finaldata$contime)]), labels = c("Thu","Fri","Sat"))
legend("topright",lty = c(1,1,1),col = c("black","red","blue" ), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),cex = 0.6,adj = 0)
dev.copy(png, file = "plot3.png")
dev.off()
